name: CD - Deploy to AWS via Terraform Cloud

on:
  push:
    branches:
      - main

jobs:
  check-ci-status:
    name: Check CI Status
    runs-on: ubuntu-latest
    outputs:
      proceed: ${{ steps.check.outputs.proceed }}
    steps:
      - name: Check Jenkins CI Status
        id: check
        run: |
          COMMIT_SHA="${{ github.sha }}"
          STATUS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/commits/${COMMIT_SHA}/status | jq -r '.state')

          echo "CI status is: $STATUS"
          if [ "$STATUS" == "success" ]; then
            echo "proceed=true" >> $GITHUB_OUTPUT
          else
            echo "CI failed. Skipping CD."
            echo "proceed=false" >> $GITHUB_OUTPUT
          fi

  deploy:
    name: Deploy Spring App via Terraform Cloud
    runs-on: ubuntu-latest
    needs: check-ci-status
    if: needs.check-ci-status.outputs.proceed == 'true'
    env:
      TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_key_name: ${{ secrets.AWS_EC2_KEY_NAME }}
      TF_CLOUD_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: Authenticate to Terraform Cloud
        run: |
          mkdir -p ~/.terraform.d
          echo '{"credentials":{"app.terraform.io":{"token":"${{ secrets.TERRAFORM_CLOUD_TOKEN }}"}}}' > ~/.terraform.d/credentials.tfrc.json

      - name: Terraform Init
        run: terraform -chdir=infra init

      - name: Terraform Plan
        run: terraform -chdir=infra plan

      - name: Terraform Apply
        run: terraform -chdir=infra apply -auto-approve
